### ISSUE TITLE
既然是轻量级定位，为嘛还要用redis？直接用python自带的sqlite吧

### ISSUE THREAD

**Issue by wonb168** [DavidTorpey/pydags#3]
想找到轻量级的调度，发现这个比较吻合我的需求。只是既然是轻量级定位，为嘛还要用redis？直接用python自带的sqlite吧

**Comment by DavidTorpey** [comment]
Hi. I chose redis just for ease of use, but you could definitely use sqlite. You can subclass [`Cache`](https://github.com/DavidTorpey/pydags/blob/main/src/pydags/cache.py#L29) and implement a sqlite-based cache.
